[versions]
junit = "4.13.2"
kotlin = "2.3.0"
xml-serialization = "0.91.3"
kotlinx-serialization = "1.9.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-serialization-xml = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xml-serialization" }
kotlinx-serialization-xml-io = { module = "io.github.pdvrieze.xmlutil:serialization-io", version.ref = "xml-serialization" }
xmlutil-core-io = { module = "io.github.pdvrieze.xmlutil:core-io", version.ref = "xml-serialization" }
test-parameter-injector = "com.google.testparameterinjector:test-parameter-injector:1.20"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
